### ISSUE TITLE
Weird letters on background of clock

### ISSUE THREAD

**Issue by ZeyadTheCoder** [ymmooot/uebersicht-calendar-jsx#4]
the letters pr are shown on the clock  
<img width="223" alt="Screen Shot 2021-06-16 at 8 40 41 PM" src="https://user-images.githubusercontent.com/24728285/122274712-28107f80-cee3-11eb-8def-4ae7b7738a5e.png">

**Comment by ymmooot** [comment]
I think you are posting the issue to wrong repository.
